@startuml get_kv_activity_diagram
start
repeat
  :Определить i-го держателя ключа;
  if (Держатель - сам узел?) then (Да)
    :Вернуть KV из локального хранилища;
    stop
  else (Нет)
    :Запросить KV от i-го держателя;
  endif
repeat while (Извлечение удалось?) is (Нет) not (Да)
:Вернуть полученный KV / Вернуть сообщение об ошибке;
stop
@enduml