@startuml put_kv_activity_diagram
start
repeat
  :Определить i-го держателя ключа;
  if (Держатель - сам узел?) then (Да)
    :Записать KV в локальное хранилище;
  else (Нет)
    :Записать KV в i-го держателя;
    if (Запись удалась?) then (Да)
    else (Нет)
        :Добавить узел в сообщение об ошибке;
    endif
  endif
repeat while (Запись произведена во всех держателей?) is (Нет) not (Да)
:Вернуть сообщение об удачной записи
ИЛИ
Вернуть сообщение об ошибке;
stop
@enduml