// Code generated by mockery v3.0.0-alpha.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LocalStorage is an autogenerated mock type for the Repository type
type LocalStorage struct {
	mock.Mock
}

// Get provides a mock function with given fields: key
func (_m *LocalStorage) Get(key string) (map[string]interface{}, error) {
	ret := _m.Called(key)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, val
func (_m *LocalStorage) Set(key string, val map[string]interface{}) error {
	ret := _m.Called(key, val)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, map[string]interface{}) error); ok {
		r0 = rf(key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewLocalStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewLocalStorage creates a new instance of LocalStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLocalStorage(t mockConstructorTestingTNewLocalStorage) *LocalStorage {
	mock := &LocalStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
